### PR TITLE
More robust file path handling

### PR DESCRIPTION
**Pull request by bart-vmware**
For a .sln below the git directory, invalid paths were generated (for example: `\src\project\file.cs` instead of `src\project\file.cs`). So I decided to dive in and make file path handling more robust when running on git changes.
By using the .NET built-in path manipulation routines, many corner cases are resolved. Such as whether a directory contains a trailing separator, the platform-dependent directory separator in use, and handling relative paths like `".\src\..\demo.sln"`.

With these changes, the following now works correctly for git changed files:
- Using a .sln in the git directory, or anywhere below it
- Using a .sln in a git subdirectory that references files in parent/peer/nested directories
- Running regitlint from the git directory or anywhere below it

Additional changes:
- Fail when the specified .sln file does not exist.
- Faster .sln detection, by aborting the scan as soon as one is found.
- The `disable-jb-path-hack` setting is no longer used: the `**/` prefix is now applied when needed per file.

To test these, I've created a testset containing several solutions, projects and C# files, which I'm attaching as a zip file here. 
[ReformatTestSet.zip](https://github.com/sethreno/ReGitLint/files/9181462/ReformatTestSet.zip)
It contains a git repo and two branches (so you can test passing git commit hashes to regitlint).

For example, put the below contents in `launchsettings.json` to debug (adapt the working directory to your local system):
```json
{
  "profiles": {
    "ReGitLint": {
        "commandName": "Project",
        "commandLineArgs": "-s ..\\SolutionInGitRoot.sln --print-command -f commits -a head -b 796717bf  -p  \"**/*.cs\"  --skip-tool-check --jb --verbosity=INFO --fail-on-diff",
        "workingDirectory": "C:\\Source\\Repos\\ReformatTestSet\\src"
    }
  }
}
```

I've verified that `Path.GetFullPath()` works on Windows with paths that exceed MAX_PATH (260 chars): It calls into [GetFullPathNameW](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfullpathnamew), which doesn't have this limitation.

Side notes:
- When using a file pattern (instead of git changed files), it gets too tricky to manipulate that based on the current directory, so it gets passed along as-is. This means its meaning depends on from which directory regitlint is run. But because we cannot assume regitlint is run from below a git repository, this seems like an acceptable compromise.
- The same applies for scanning .sln files, which may be picked up from another git repo entirely because it scans up to the drive root. I didn't want to constrain that to the git directory for backwards compatibility (running `regitlint -p "**/*.cs"` works without a git repo today).
- It would be nice if the regitlint repo contained Resharper formatting settings (in .editorconfig or .DotSettings file), so I can adhere to the style preferences.
- I suspect the .NET 5 target can be removed, it is no longer supported by Microsoft.

### CODE REVIEW

**Comment by bart-vmware** [comment]
@sethreno Would you have time to get this in somewhere this week? The bug is blocking my project. I've tested quite thoroughly, so I think this is safe (and non-breaking).

**Comment by sethreno** [comment]
@bart-vmware Thanks for this really well explained PR. I'll check it out today, test, and get a new nuget published. Sorry I couldn't get to it earlier in the week.

Regarding your last two points:

* there is a .editorconfig file in the regitlint repo. Did you miss it or are you saying it's missing some settings you think should be there?
* I removed .net 5 after it went out of support and added it back per someone's request. I'll have to look that one up to see if it's still valid.

Also, would you have any interest in taking over as maintainer of this project?

**Comment by sethreno** [comment]
Published to nuget as 6.1.1. Thanks again!

**Comment by bart-vmware** [comment]
@sethreno Thank you for finding the time to get this released. I'm happy to hear that you appreciate my efforts and that you have confidence in me taking over maintenance of this project. Unfortunately my time is quite limited at the moment too.

When contributing to projects I'm not an owner of, I try to change as little as possible. While ReGitLint is a fine tool that does its job, I've been thinking about starting a similar project where I'd do many things quite differently; it wouldn't be compatible with the current version. That's going to take a lot of effort. I don't know if that's ever going to happen, but I can't justify doing that during working hours as things are now, and I'm already running several other open source projects in private time.

I wouldn't mind if you made me co-maintainer of ReGitLint, so I can release simple fixes when they pop up (I would still appreciate a second pair of eyes, though). In that case, please use my personal account [bkoelman](https://github.com/bkoelman). I'm just not in a position to commit to maintaining this project and taking responsibility for its future.

> there is a .editorconfig file in the regitlint repo. Did you miss it or are you saying it's missing some settings you think should be there?

I've opened the solution in VS 2022 and reformatted using Resharper 2022.1.2 [last time](https://github.com/sethreno/ReGitLint/pull/25). But somehow that doesn't match the styling you expect, so I suspect that some settings are missing in .editorconfig. I don't have any custom Resharper settings at the computer or user level.

> I removed .net 5 after it went out of support and added it back per someone's request. I'll have to look that one up to see if it's still valid.

I don't mind targeting .NET 5, just thought I'd point it out in case you forgot about it.

**Comment by sethreno** [comment]
@bart-vmware  I added you (bkoelman) as a contributor.

> I've opened the solution in VS 2022 and reformatted using Resharper 2022.1.2 https://github.com/sethreno/ReGitLint/pull/25. But somehow that doesn't match the styling you expect, so I suspect that some settings are missing in .editorconfig. I don't have any custom Resharper settings at the computer or user level.

Thanks for bringing this up! I don't use visual studio and I'm very intrigued as to why it didn't respect .editorconfig settings. Here are a couple lines from that commit that didn't match .editorconfig that would could use to troubleshoot:

        SolutionFile = Path.GetRelativePath(Environment.CurrentDirectory, SolutionFile);
        HashSet<string> filePathsRelativeToGitDirectory = new HashSet<string>();

Running cleanup changes these to:

        SolutionFile =
            Path.GetRelativePath(Environment.CurrentDirectory, SolutionFile);
        var filePathsRelativeToGitDirectory = new HashSet<string>();

The .editorconfig settings in play there are

        max_line_length=80
        csharp_style_var_when_type_is_apparent=true:hint

I always review the changes made by running cleanup and often manually change the way lines are broken. In this case I manually changed this block. I shortened the long variable name to prevent additional line breaks further down in the file that I thought negatively affected readability. This resulted in:

        SolutionFile = Path.GetRelativePath(
            Environment.CurrentDirectory, SolutionFile);

        // paths are relative to the git root directory
        var filePaths = new HashSet<string>();

**Comment by bkoelman** [comment]
I can't reproduce the formatting difference anymore. It was probably related to the renames.

**Pull request merged**
