### PR TITLE
Add support for globally installed JB Resharper tool

### PR DESCRIPTION
**Pull request by fehrm**
Suggestion for the change needed for issue #19

The message is optional but might be good to know if it uses local or global Resharper

### CODE REVIEW

**Comment by sethreno** [comment]
@fehrm Thanks for the contribution.

This won't completely resolve the issue though. The DoesJbToolExist function only validates that jb is installed. The code that actually makes the call will still need to be modified:
here: https://github.com/sethreno/ReGitLint/blob/master/ReGitLint/Cleanup.cs#L384
and here: https://github.com/sethreno/ReGitLint/blob/master/ReGitLint/Cleanup.cs#L400

Also, for my use case I do not want it to fallback on the global tool. It's best practice to use a local tool pinned to a specific version because the formatting behavior of resharper changes with each version. Using a global tool in a ci pipeline will make the builds non-repeatable.

What do you think about making this behavior opt-in with an option? Something like --use-global

**Comment by fehrm** [comment]
@sethreno I agree that an option is preferable, I added an option called --use-global or -g, and made the other changes you asked for. Thanks for pointing out I missed them!

I took the liberty of bumping the version to 6.0.8, is that OK? What version do you want?

**Comment by sethreno** [comment]
@fehrm I got this merged and released in v6.0.8. I needed to tweak a couple things. Ironically one of them was formatting. Looks like you didn't run regitlint after making your changes! :)

**Comment by sethreno** [comment]
@fehrm  Also, if you're finding ReGitLint useful please star it. Thanks!

**Pull request merged**
