### PR TITLE
Allow combination of staged files, unstaged files and commit range

### LINKED ISSUE #15: Feature request: allow diff against commit hash (range), including staged/unstaged changes
Today cleanup can be run on either staged files (`-f staged`), modified files in the working tree (`-f modified`), the set of changed files in a single commit (`-a 3796556`), or the set of changed files between two commits (`-a 6708090 -b 3796556`).

I would like to be able to run against the set of changed files in one or more commits, plus the set of staged and the set of unstaged files.

This speeds up local development, compared to running a full cleanup. I would pass the commit hash of the base branch and HEAD, so that it reformats all files in those commits plus the files (staged/unstaged) that I'm still working on.

### PR DESCRIPTION
**Pull request by bart-vmware**
Fixes #15.

### CODE REVIEW

**Comment by bart-vmware** [comment]
@sethreno tested locally and seems to work fine.

**Comment by bkoelman** [comment]
@sethreno Any chance this can be reviewed, merged and released somewhere in the next few days? I need this for work, but prefer not to create my own version.

**Comment by sethreno** [comment]
Thanks for the PR. I merged this and released in 6.1.0. Sorry for the delay, very busy lately.

**Comment by bart-vmware** [comment]
Thanks a lot!

**Pull request merged**
